// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsxslyewvihgcsdceonu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeHNseWV3dmloZ2NzZGNlb251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODkzNjYsImV4cCI6MjA2ODI2NTM2Nn0.o_V2KuLZnA15vshL_7t5dKdevEsdTIVQUEjqI4z_1UA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});